In [ ]:
#create a array
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A=np.linspace(2,8,10).reshape(2,5)
print(A)

[[2.         2.66666667 3.33333333 4.         4.66666667]
 [5.33333333 6.         6.66666667 7.33333333 8.        ]]


In [ ]:
B=np.array([45,49,67,89,172,347,18,3]).reshape(2,2,2)
print(B)

[[[ 45  49]
  [ 67  89]]

 [[172 347]
  [ 18   3]]]


In [ ]:
B=np.array([68,53,23,39,78,16,71])
B.resize(2,2,2)       #change the shape of original array
#reshape  -  changes needs saving in another varaiable
print(B)

[[[68 53]
  [23 39]]

 [[78 16]
  [71  0]]]


In [ ]:
A=np.array([64,23,3,79,16,24])
B=np.array([13,8,56,34,35,55])
C=A-B
print(A-B)

[ 51  15 -53  45 -19 -31]


In [ ]:
A=np.array([64,23,3,79,16,24])
B=np.array([13,8,56,34,35,55])    #list will throw an error
C=A+B
print(C)

[ 77  31  59 113  51  79]


In [ ]:
A=np.array([64,23,3,79,16,24]).reshape(2,3)
B=np.array([13,8,56,34,35,55]).reshape(2,3)
print("addition:")
print(A+B)
print("subtraction")
print(A-B)
print("mulitiplication:")
C=(A*B)
print("thank you")
print(C)

addition:
[[ 77  31  59]
 [113  51  79]]
subtraction
[[ 51  15 -53]
 [ 45 -19 -31]]
mulitiplication:
thank you
[[ 832  184  168]
 [2686  560 1320]]


In [ ]:
A=np.array([64,23,3,79,16,24,35,52,21,49,35,43]).reshape(4,3)
B=np.array([13,8,56,34,35,55,34,13,98,35,49,36]).reshape(4,3)
print(A)
print("____________________________________")
print(A.max(axis=0))          #axis 0-column wise
print("___________________________________")
print(A.max(axis=1))          #axis 1-row wise

[[64 23  3]
 [79 16 24]
 [35 52 21]
 [49 35 43]]
____________________________________
[79 52 43]
___________________________________
[64 79 52 49]


In [ ]:
A=np.array([64,23,3,79,16,24,35,52,21,49,35,43]).reshape(4,3)
B=np.array([13,8,56,34,35,55,34,13,98,35,49,36]).reshape(4,3)
print(A)
print("____________________________________")
print(A.min(axis=0))          #axis 0-column wise
print("___________________________________")
print(A.min(axis=1))          #axis 1-row wise

[[64 23  3]
 [79 16 24]
 [35 52 21]
 [49 35 43]]
____________________________________
[35 16  3]
___________________________________
[ 3 16 21 35]


In [ ]:
A=np.array([64,23,3,79,16,24])
B=np.array([13,8,56,34,35,55])
print(A)
print("_______________________")
print(B)
print("After vertically stacking the arrays")
print(np.vstack((A,B)))
print("after horizontally stacking the arrays")
print(np.hstack((A,B)))
print("using axis operation :")
print(np.stack((A,B),axis=0))

[64 23  3 79 16 24]
_______________________
[13  8 56 34 35 55]
After vertically stacking the arrays
[[64 23  3 79 16 24]
 [13  8 56 34 35 55]]
after horizontally stacking the arrays
[64 23  3 79 16 24 13  8 56 34 35 55]
using axis operation :
[[64 23  3 79 16 24]
 [13  8 56 34 35 55]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("creating a  dstack")
print(np.dstack((A)))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
creating a  dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
# splitting arrays !
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting ")
print(np.vsplit(A,3))
print("own index cutting matix after")
print(np.vsplit(A,(2,5)))
print("another splitting")
print(np.vsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting 
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]
own index cutting matix after
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]
another splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#row or hoziontal
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting ")
print(np.hsplit(A,3))
print("own index cutting matix after")
print(np.hsplit(A,(2,5)))
print("another splitting")
print(np.hsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting 
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]
own index cutting matix after
[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([], shape=(6, 0), dtype=int64)]
another splitting
[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([], shape=(6, 0), dtype=int64)]


In [ ]:
#arrray argument size (arguments max size)
A=np.arange(30).reshape(5,6 )
print(A)                              #postitio 0000
                                                #1111
print(A.argmax(axis=0))


#arrray argument size (arguments max size)
A=np.arange(30).reshape(5,6 )
print(A)                                      #position 0123
                                                       # 0123
print(A.argmax(axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[4 4 4 4 4 4]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[5 5 5 5 5]


In [ ]:
#arrray argument size (arguments min size)
A=np.arange(30).reshape(5,6 )
print(A)
print(A.argmin(axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[0 0 0 0 0]


In [ ]:
Statistics

In [ ]:
#mean,median,std,variance
A=np.array([32,35,89,12,37,67])
print("mean:",np.mean(A))
print("median:",np.median(A))
print("Standard Dev:",np.std(A))
print("variance:",np.var(A))

mean: 45.333333333333336
median: 36.0
Standard Dev: 25.302612952464457
variance: 640.2222222222222


Trigonometry

In [ ]:
A=np.pi     #pi=180
print(A)  #radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B=np.array([np.pi/4,np.pi/2,np.pi/6])
np.rad2deg(B)

array([45., 90., 30.])

In [ ]:
B=np.array([np.pi/4,np.pi/2,np.pi/6])
np.deg2rad(B)

array([0.01370778, 0.02741557, 0.00913852])

In [ ]:
B=np.array([np.pi/4,np.pi/2,np.pi/6,0])
print("sin of array is {np.sin(B)}")

<>:2: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
<>:2: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
<ipython-input-105-1dc8530c95d3>:2: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  print("sin of array is "(np.sin(B)))


TypeError: 'str' object is not callable

In [ ]:
np.arcsin(1)      #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)        #cos^-1

0.0

In [ ]:
np.arctan(1)            #tan^-1

0.7853981633974483

In [ ]:
a=6
b=4
print(np.hypot(a,b))            #hypothesis

7.211102550927978


SEARCHING


In [ ]:
A=np.array([34,4,358,35,35,38])
print(np.where(A==21))

(array([], dtype=int64),)


In [ ]:
A=np.array([34,4,358,35,35,38])
print(np.where(A%2==0))

(array([0, 1, 2, 5]),)


In [ ]:
#sorted array = 12,24,37,54,57,64,89,98;
A=np.array([54,89,57,64,12,98,37,24])
print(np.searchsorted(A,24))


5


Linear algebra and Ufunc

In [ ]:
A=np.array([54,89,57,64,12,98,37,24])
B=np.array([32,35,89,12,37,67,10,50])
print(np.add(A,B))            #addition
print(np.subtract(A,B))       #subtract
print(np.divide(A,B))         #quotient
print(np.mod(A,B))            #remanider
print(np.divmod(A,B))         #q and r
print(np.diff(A))              #differences

[ 86 124 146  76  49 165  47  74]
[ 22  54 -32  52 -25  31  27 -26]
[1.6875     2.54285714 0.64044944 5.33333333 0.32432432 1.46268657
 3.7        0.48      ]
[22 19 57  4 12 31  7 24]
(array([1, 2, 0, 5, 0, 1, 3, 0]), array([22, 19, 57,  4, 12, 31,  7, 24]))
[ 35 -32   7 -52  86 -61 -13]


In [ ]:
A=np.array([60,25,89,10,6,73])
print(np.sort(A))         #sorting the array

[ 6 10 25 60 73 89]


In [ ]:
A=np.array([60,25,89,10,6,73])
B=np.array([50,10,59,78,26,41])       #sorting and common elements remove
print(np.setdiff1d(A,B))

[ 6 25 60 73 89]


Rounding


In [ ]:
a=np.trunc([-6.6654,5.555])         #truncate
print(a)


[-6.  5.]


In [ ]:
a=np.fix([-6.6654,5.555])         #fixing
print(a)

[-6.  5.]


In [ ]:
a=np.around([-6.6654,5.555])
print(a)


[-7.  6.]


In [ ]:
a=np.floor([-6.6654,5.555])
print(a)


[-7.  5.]


In [ ]:
a=np.ceil([-6.6654,5.555])
print(a)


[-6.  6.]


Rounding using arrays


In [ ]:
a=np.array([-6.6654,5.555])
print(np.trunc(a))


[-6.  5.]


In [ ]:
a=np.array([-6.6654,5.555])
print(np.fix(a))


[-6.  5.]


In [ ]:
a=np.array([-6.6654,5.555])
print(np.around(a))


[-7.  6.]


In [ ]:
a=np.array([-6.6654,5.555])
print(np.floor(a))


[-7.  5.]


In [ ]:
a=np.array([-6.6654,5.555])
print(np.ceil(a))


[-6.  6.]


More Functions !

In [ ]:
a=np.array([52,35,16,98])         #addition of one to one element like this 52+35=ans  ,52+35+16=ans
print(np.cumsum(a))


[ 52  87 103 201]


In [ ]:
a=np.array([34,6,24,79,32,56])  #same as same above process but changes mulitiplication
print(np.cumprod(a))


[       34       204      4896    386784  12377088 693116928]


In [ ]:
print(np.lcm(64,89))
print(np.gcd(855,144))

5696
9


In [ ]:
a=np.array([25,238,5,796,25,35])
print(np.cumprod(a))


[         25        5950       29750    23681000   592025000 20720875000]


In [ ]:
a=np.array([25,238,5,796,25,35])
print(np.gcd.reduce (a))


1


In [ ]:
a=np.array([[25,23],[5,79]])
print(np.linalg.inv(a))


[[ 0.04247312 -0.01236559]
 [-0.00268817  0.01344086]]


Random

In [ ]:
from numpy import random rd

SyntaxError: invalid syntax (<ipython-input-44-7937bb647672>, line 1)

JOINS !

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1*4 + 2*5 +3*6
print(np.inner(A,B))

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1*4 + 2*5 +3*6
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])
B=np.array([3,7,8])
print(np.cross(A,B))

[-5  1  1]


Sets
