In [ ]:
a=10
print("i am " ,a, "is years old ")


i am  10 is years old 


In [ ]:
#arithmetic two int variables
a=int(input("enter a  value:"))
b=int(input("enter b value:"))
print("sum is ",(a+b))
print("differences is",(a-b))
print("product is ",(a*b))
print("quotient is ",(a/b))
print("remainder is ",(a%b))
print("power of a to be is",(a**b))
print("floor div",(a//b))

enter a  value:10
enter b value:50
sum is  60
differences is -40
product is  500
quotient is  0.2
remainder is  10
power of a to be is 100000000000000000000000000000000000000000000000000
floor div 0


In [ ]:
# take a salary from the user if the salary is more than 50,000 their is the 10% tax .print is final salary
s=int(input("enter salary:"))
c=s*10/100
if s>=50000:
  v=s-c
  print("tax is",v)
else:
  print("less salary 50k so no tax ",s)

enter salary:67000
tax is 60300.0


In [ ]:
# get the salary from user if the salary the more than equal 50000 apply 10% tax detection  ,if the salary is less than 50000 apply 5% tax,if the salary is more than 70000 apply 12% tax,if the salary exists one lakh print your promoted to next level
s=int(input("enter the salary:"))
if s<50000:
  print("salary is  ",s-(s*0.5))
elif s>=  50000 and s<=70000:
  print("salary is",s-(s*0.1))
elif s>70000 and s<=100000:
  print("salary is",s-(s*0.12))
else:
  print("PROMOTED !!!")

enter the salary:75000
salary is 66000.0


In [ ]:
for i in range (1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# tables for loop:
t=int(input("enter num:"))
for i in range(1,11):
  print(t,"x",i,"=",t*i)

enter num:8749749
8749749 x 1 = 8749749
8749749 x 2 = 17499498
8749749 x 3 = 26249247
8749749 x 4 = 34998996
8749749 x 5 = 43748745
8749749 x 6 = 52498494
8749749 x 7 = 61248243
8749749 x 8 = 69997992
8749749 x 9 = 78747741
8749749 x 10 = 87497490


In [ ]:
# table while loop
t=int(input("enter num:"))
i=1
while i<11:
  print(t,"X",i,"=",t*i)
  i=i+1


enter num:8
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
8 X 10 = 80


In [ ]:
# create a list(heterogenus):
l1=[1,"kill",89,"chat",9.1,True]
for i in l1:
  print(i)

1
kill
89
chat
9.1
True


In [ ]:
#list (mutable):
l1.append("appended") #add element a back of the list
print(l1)
# list (insert):      synatx: listname.insert(index,element)
l1.insert(4,"hi")
print(l1)

[1, 'kill', 89, 'chat', 'hi', 'hi', 'hi', 9.1, True, 'appended', 'appended', 'appended', 'appended']
[1, 'kill', 89, 'chat', 'hi', 'hi', 'hi', 'hi', 9.1, True, 'appended', 'appended', 'appended', 'appended']


In [ ]:
#create a list and adding to lists
l2=["anvesh","sai"]
l1.extend(l2)  #l1=l1+l2              syntax:listname.extend(list2)
print(l1)

[1, 'kill', 89, 'chat', 'hi', 'hi', 'hi', 'hi', 9.1, True, 'appended', 'appended', 'appended', 'appended', 'anvesh', 'sai']


In [ ]:
#remove a element or poped element in list
l1.pop(2)       #pop syntax:listname.pop(index)
print(l1)


[1, 'kill', 'hi', 'hi', 'hi', 9.1, True, 'appended', 'appended', 'appended', 'appended', 'anvesh', 'sai']
[1, 'hi', 'hi', 'hi', 9.1, True, 'appended', 'appended', 'appended', 'appended', 'anvesh', 'sai']


In [ ]:
#remove
l1.remove("hi")       #remove syntax:listname.remove(element)
print(l1)

[1, 'hi', 'hi', 9.1, True, 'appended', 'appended', 'appended', 'appended', 'anvesh', 'sai']


In [ ]:
#clear a list
l1.clear()
print(l1)

[]


In [ ]:
#create a list of random 10 integer elements print thier squares.save this square in new list
l1=[5,16,78,24,45,27,21,95,65,37]
res=[]
for i in l1:
  res.append(i*i)
  print(res)

[25]
[25, 256]
[25, 256, 6084]
[25, 256, 6084, 576]
[25, 256, 6084, 576, 2025]
[25, 256, 6084, 576, 2025, 729]
[25, 256, 6084, 576, 2025, 729, 441]
[25, 256, 6084, 576, 2025, 729, 441, 9025]
[25, 256, 6084, 576, 2025, 729, 441, 9025, 4225]
[25, 256, 6084, 576, 2025, 729, 441, 9025, 4225, 1369]


In [ ]:
#another way above program
#lc
#newlist=[output for]
l1=[46,456,53,464,44,946,46]
res=[i*i for i in l1]
print(res)

[2116, 207936, 2809, 215296, 1936, 894916, 2116]


In [ ]:
#another way above program
#lc
#newlist=[(st of if) if (cond) else (st of else for)]
l1=[65,35,37,12,68,23]
res=[i*i if i>50 else 'x' for i in l1]
print(res)


[4225, 'x', 'x', 'x', 4624, 'x']


In [ ]:
#take the salary from the user if the salary less than 50k 10% tax otherwise 15% tax
s=[324565,58000,75000,45000]
res= [i-i*0.1 if i<50000 else i-i*0.15 for i in s]
print(res)

[275880.25, 49300.0, 63750.0, 40500.0]


In [ ]:
dict1={'mentor':'Jwalitha',10:'gagan',20:'jogendra',30:'harish'}
print(dict1)

{'mentor': 'Jwalitha', 10: 'gagan', 20: 'jogendra', 30: 'harish'}


In [ ]:
dict1={10:'gagan',20:'jogendra',30:'harish'}
print(dict1.values())
print(dict1.keys())
print(dict1[10])


dict_values(['gagan', 'jogendra', 'harish'])
dict_keys([10, 20, 30])
gagan


In [ ]:
dic3={'Dept':'CSE','details':{'years':'II','sec':'D','count':71}}
print("year is",dic3["details"]["year"])
print("section is",dic3["details"]["sec"])
print("strength is ",dic3["details"]["count"])



KeyError: 'year'

In [ ]:
idl = [80,56,64,24,52]
names=['gagan','sai','jogendra','anvesh']
zip=(zip(idl,names))
for i in zip:
  print(i)

(80, 'gagan')
(56, 'sai')
(64, 'jogendra')
(24, 'anvesh')


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4])     #1D array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
#numpy     2D array
import numpy as np
A=np.array([[25,26,78,1],[58,51,18,37]])
#elements in each row=columns
print(A.ndim)
print(A.shape)
print(A)

2
(2, 4)
[[25 26 78  1]
 [58 51 18 37]]


In [ ]:
# numpy 3D array
import numpy as np
x=np.array([[[10],[20],[30]],[[40],[50],[60]],[[10],[20],[3]],[[40],[50],[60]]])
print(x.ndim)
print(x.shape)
print(x)

3
(4, 3, 1)
[[[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]

 [[10]
  [20]
  [ 3]]

 [[40]
  [50]
  [60]]]


In [ ]:
x=np.ones((2,3))  #2d array
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


x=np.zeros((4,5,2))   #3d array
print(x)

In [ ]:
x=np.eye(4)     #identity matrics
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
x=np.arange(1,10,2)   #start,stop,step
print(x)
print(type(x))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all number are d
x=np.arange(8,1001,8)     #8th table upto 1000 range
print(x)
print(type(x))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
#spliting a range into n numbers with common differences
x=np.linspace(50,54,50)                     #upper,lower,n numbers
print(x)

[50.         50.08163265 50.16326531 50.24489796 50.32653061 50.40816327
 50.48979592 50.57142857 50.65306122 50.73469388 50.81632653 50.89795918
 50.97959184 51.06122449 51.14285714 51.2244898  51.30612245 51.3877551
 51.46938776 51.55102041 51.63265306 51.71428571 51.79591837 51.87755102
 51.95918367 52.04081633 52.12244898 52.20408163 52.28571429 52.36734694
 52.44897959 52.53061224 52.6122449  52.69387755 52.7755102  52.85714286
 52.93877551 53.02040816 53.10204082 53.18367347 53.26530612 53.34693878
 53.42857143 53.51020408 53.59183673 53.67346939 53.75510204 53.83673469
 53.91836735 54.        ]


In [ ]:
#
t = ("apple", "banana", "cherry", "apple", "cherry")
print(t)

('apple', 'banana', 'cherry', 'apple', 'cherry')


In [ ]:
#concatenating 2 tuples
tuple1 = (0, 1, 2, 3)
tuple2 = ('python', 'geek')
print(tuple1 + tuple2)

(0, 1, 2, 3, 'python', 'geek')


In [ ]:
t1=('a','b','c')
t2=(1,2,3,4)
print(t1+t2)

('a', 'b', 'c', 1, 2, 3, 4)


In [ ]:
# Code for concatenating 2 tuples
tuple1 = (0, 1, 2, 3)
tuple2 = ('python', 'geek')

# Concatenating above two
print(tuple1 + tuple2)


(0, 1, 2, 3, 'python', 'geek')


In [ ]:
min(t1)
max(t2)

4

In [ ]:
a=[31,6,34,68,54]
#print(sorted(a))

print(a)

[31, 6, 34, 68, 54]


sets


In [ ]:
myset = {"apple", "banana", "cherry"}

In [ ]:
thisset = {"apple", "banana", "cherry"}
print(thisset)


In [ ]:
thisset = {"apple", "banana", "cherry", "apple"}

print(thisset)

In [ ]:
thisset = {"apple", "banana", "cherry", True, 1, 2}

print(thisset)

In [ ]:
thisset = {"apple", "banana", "cherry", False, True, 0}

print(thisset)

In [ ]:
thisset = {"apple", "banana", "cherry"}

print(len(thisset))

3
